### ISSUE TITLE
Security fixes

### ISSUE THREAD

**Issue by OskarLebuda** [atomiomi/fontellizr#22]
This project uses the `xmldom` package which has a lot of security updates during the years.
I didn't found any call of this lib inside of project - that's so maybe you can delete this package?
![image](https://github.com/atomiomi/fontellizr/assets/10373127/25a1f10b-94ca-4a82-b3d1-b596123d23ac)

`npm audit` report that package as critical one. 
| package | severity | version | cwe | cvss |
| --- | --- | --- | --- | --- |
| `xmldom`| critical | `<=0.6.0` | `CWE-20`, `CWE-1288` | `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H`  |
| `xmldom`| moderate | `<0.5.0` | `CWE-115`, `CWE-436` | `CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N`  |
| `xmldom`| moderate | `<=0.6.0` | `CWE-116` | `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N`  |

**Comment by atomiomi** [comment]
It's used here https://github.com/atomiomi/fontellizr/blob/master/vendor/_svg_image_flatten.js
Not sure if I can safely update it, haven't checked this lbi for a long time sorry

**Comment by OskarLebuda** [comment]
Ohh I see. The package has been moved into `@xmldom/xmldom` https://github.com/xmldom/xmldom. Let me know if you need some help with that migration. 

Another critical issue is from `decompress` which also has security updates:
| package | severity | version | cwe | cvss |
| --- | --- | --- | --- | --- |
| `decompress`| critical | `<4.2.1` | `CWE-22`, `CWE-59` | `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H`  |

**Comment by atomiomi** [comment]
You could prepare PR if you have time, I'm currently not support ing this package

**Comment by OskarLebuda** [comment]
@atomiomi  approve PR and make release please.
